#!/bin/bash

url="http://mygitserver.com/api"
id="6"
key="xxxxxxxxxxxxxxxxx"
secret="xxxxxxxxxxxxx"

structurizr-push $url $id $key $secret "/workspace/model/Identity&AccessManagement/License/workspace.dsl"




