#!/bin/bash

url="http://mygitserver.com/api"
id="10"
key="xxxxxx"
secret="xxxxxxxxxxxxx"
district="Identity&AccessManagement"
application="Identity"
workspace="/workspace/model/$district/$application/workspace.dsl"

structurizr-push $url $id $key $secret $workspace




